### ISSUE TITLE
Change all checks for empty strings

### ISSUE THREAD

**Issue by andream16** [AndreaM16/aws-sdk-go-bindings#13]
Change checks fro empty strings from:

```
someString := ""

if len(someString) == 0 {
    ...
}
```
to 

```
someString := ""

if someString == "" {
    ...
}
```

to have a more [idiomatic go](https://dmitri.shuralyov.com/idiomatic-go#empty-string-check).

**Comment by WerWolv** [comment]
I'll take on this issue
