### ISSUE TITLE
Add DynamoDB example in examples

### ISSUE THREAD

**Issue by andream16** [AndreaM16/aws-sdk-go-bindings#5]
Add an example for DynamoDB in `examples` like I did with `s3`.

**Comment by TvtTest** [comment]
This Node.js code example shows:-How to add an item in a DynamoDB table.

// Load the AWS SDK for Node.js
var AWS = require('aws-sdk');
// Set the region 
AWS.config.update({region: 'REGION'});

// Create the DynamoDB service object
ddb = new AWS.DynamoDB({apiVersion: '2012-10-08'});

var params = {
  TableName: 'TABLE',
  Item: {
    'CUSTOMER_ID' : {N: '001'},
    'CUSTOMER_NAME' : {S: 'Richard Roe'},
  }
};

// Call DynamoDB to add the item to the table
ddb.putItem(params, function(err, data) {
  if (err) {
    console.log("Error", err);
  } else {
    console.log("Success", data);
  }
});

To run the example, type the following at the command line.
node ddb_putitem.js

**Comment by andream16** [comment]
I'm sorry but I didn't understand what you mean with that NodeJS example. I mean, create a new example in `examples` directory like I did with `s3`

**Comment by TvtTest** [comment]
sorry, where is the example directory.

**Comment by andream16** [comment]
You can find it [here](https://github.com/AndreaM16/aws-sdk-go-bindings/tree/master/examples). Try something like:
 - Create a table with an index
 - Put some item into it, like a User
 - Get the same user from it and print the result

**Comment by TvtTest** [comment]
create table in DynamoDB in java
  
  01
	public class CreateProductTable implements Task {
02
	 
03
	    @Override
04
	    public void run(String[] args, AmazonDynamoDB dynamodb) {
05
	 
06
	        ArrayList<AttributeDefinition> attributeDefinitions = new ArrayList<>();
07
	        attributeDefinitions.add(new AttributeDefinition()
08
	                .withAttributeName("ID").withAttributeType("S"));
09
	 
10
	        ArrayList<KeySchemaElement> keySchema = new ArrayList<>();
11
	        keySchema.add(new KeySchemaElement()
12
	                .withAttributeName("ID").withKeyType(KeyType.HASH));
13
	 
14
	        CreateTableRequest createTableReq = new CreateTableRequest()
15
	                .withTableName("Product")
16
	                .withAttributeDefinitions(attributeDefinitions)
17
	                .withKeySchema(keySchema)
18
	                .withProvisionedThroughput(new ProvisionedThroughput()
19
	                        .withReadCapacityUnits(10L)
20
	                        .withWriteCapacityUnits(5L));
21
	        CreateTableResult result = dynamodb.createTable(createTableReq);
22
	        System.out.println(result.toString());
23
	    }
24
	}
	
	
Insert, select and delele from table

01
	public class InsertProducts implements Task {
02
	    @Override
03
	    public void run(String[] args, AmazonDynamoDB dynamodb) {
04
	        DynamoDB dynamoDB = new DynamoDB(dynamodb);
05
	        Table table = dynamoDB.getTable("Product");
06
	 
07
	        String uuid1 = UUID.randomUUID().toString();
08
	        Item item = new Item()
09
	                .withPrimaryKey("ID", uuid1)
10
	                .withString("Name", "Apple iPhone 7")
11
	                .withNumber("Price", 664.9);
12
	        table.putItem(item);
13
	 
14
	        String uuid2 = UUID.randomUUID().toString();
15
	        item = new Item()
16
	                .withPrimaryKey("ID", uuid2)
17
	                .withString("Name", "Samsung Galaxy S8")
18
	                .withNumber("Price", 543.0);
19
	        table.putItem(item);
20
	 
21
	        item = table.getItem("ID", uuid1);
22
	        System.out.println("Retrieved item with UUID " + uuid1 + ": name="
23
	                + item.getString("Name") + "; price=" + item.getString("Price"));
24
	        item = table.getItem("ID", uuid2);
25
	        System.out.println("Retrieved item with UUID " + uuid2 + ": name="
26
	                + item.getString("Name") + "; price=" + item.getString("Price"));
27
	 
28
	        table.deleteItem(new PrimaryKey("ID", uuid1));
29
	        table.deleteItem(new PrimaryKey("ID", uuid2));
30
	 
31
	        System.out.println(table.describe());
32
	    }
33
	}
	
Output 	:-
1 Retrieved item with UUID 7dc5be93-213b-4b16-95f9-5ee7381b219d: name=Apple iPhone 7; price=664.9
2 Retrieved item with UUID 06fbf030-93f0-48ca-805f-2e627d72faf4: name=Samsung Galaxy S8; price=543

**Comment by andream16** [comment]
I appreciate the comment but I think you didn't understand fully what you need to do. You need to:
 -  fork the project
 -  create a new `dynamodb.go` file inside of `example` folder
 -  use actual go code and use `aws-sdk-go-bindings` to build the example
