### ISSUE TITLE
Rename all custom error names to simple err

### ISSUE THREAD

**Issue by andream16** [AndreaM16/aws-sdk-go-bindings#8]
Rename all `someCoolErr := someCoolFuncReturningError()` to simple `err := someCoolFuncReturningError()` to be more idiomatic.

**Comment by jerdog** [comment]
I was looking at taking this on, but had a question for you - wouldn't creating multiple `err` names in the same module create some issues? Or are you ok with the entire app sharing the same err name?

**Comment by andream16** [comment]
@jerdog Go ahead! No, I guess it will not cause issues at all. There are some parts of the code like [sqs/service.go](https://github.com/AndreaM16/aws-sdk-go-bindings/blob/master/pkg/aws/sqs/service.go) at function `SQSCreateQueue` where, for instance I used stuff like `input, inputErr := NewCreateQueueInput(queue)` instead of a more idiomatic `input, err := NewCreateQueueInput(queue)`.

**Comment by jerdog** [comment]
got it. ok makes sense.

**Comment by andream16** [comment]
@jerdog any news?

**Comment by jerdog** [comment]
I'm sorry - I haven't been able to get to it - will try. Had started and
gotten through a LOT of it but haven't been able to finish given my work
and travel schedule
