### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by andream16** [AndreaM16/aws-sdk-go-bindings#9]
Use test cases and table testing to fully test cover Exported functions. Stop writing huge tests that can be written in less line thanks to [table testing](https://github.com/golang/go/wiki/TableDrivenTests).

**Comment by vittorius** [comment]
Hey. I can take this one if you're OK with the fact I'm pretty new to Go (but I have experience in C#, Python, Ruby, JS).

**Comment by andream16** [comment]
Hey, go for it. Check some examples of `table` testing like the following.

Let's say you have a function that returns `true` if the passed value is found and `false` otherwise:

```
func IsPresent(title string) bool {
    
    words := map[string]string{
        "hey" : "",
        "there" : "",
    }
    
    _, found := words[title]

    return found

}
```
 
Then you'll have a test like

```
import (
    "testing"
    "github.com/stretchr/testify/assert"
)

func TestIsPresent(t *testing.T) {

    tests := []struct{
        name string
        title string
        expected bool
    } {
        { name: "Should return true", title: "hello", expected: true },
        { name: "Should return true", title: "there", expected: true },
        { name: "Should return false", title: "cat", expected: false },
    }

    for _, v := range tests {
  
        t.Run(v.name, func(t *testing.T){
           assert.Equal(t, v.expected, IsPresent(v.title))
        })

    }

}

```

**Comment by vittorius** [comment]
Thanks!

**Comment by vittorius** [comment]
Hi @AndreaM16. I'm sorry to admit the I won't have time to accomplish this on time or ever - too much load at my job and beyond. Please consider this issue free for any other dev to work on. If I can help your project via any kind of donation, please tell. Thanks for the understanding.

**Comment by andream16** [comment]
@vittorius I understand. Thanks for letting me know. Best of luck.
